import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Import Montserrat Google Font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "300", "600", "800", "900"], // Specify the weights you need
  variable: "--font-montserrat", // Use a CSS variable for Montserrat
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>{children}</body>
    </html>
  );
}
